name: Deploy Syntax & Coffee Theme to IONOS (SFTP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {} 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SFTP Deploy (theme only)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USER }}
          password: ${{ secrets.IONOS_PASS }}
          port: 22
          local_path: ./themes/syntax-and-coffee
          remote_path: /themes/syntax-and-coffee
          sftp_only: true
          exclude: ".git,.github,.DS_Store,*.log,node_modules"